---

# TODO: implement 'default' project with cleanup job

# TODO: implement templates for projects with pipelines/templates to reduce copy-paste in each project 

- include:
    - templates.yaml

- project:
    name: tungstenfabric
    nightly:
      templates:
        - build-from-src-centos
        - test-unit
        - test-unit-ui
        - k8s-manifests
        - ansible-k8s
        - ansible-os
        - helm-k8s
        - helm-os
        - juju-k8s
        - juju-os        
        - rhosp
        - cleanup
      jobs:
        publish-centos-nightly:
          job-name: publish
          depends-on:
            - build-centos
        aquascan-rhel-nightly:
          job-name: aquascan
          depends-on:
            - build-rhel
          vars:
            TAG_SUFFIX: -rhel
      post-jobs:
        publish-centos-stable:
          job-name: publish
        cleanup-pipeline-workers:
          depends-on:
            - publish-centos-stable

- project:
    name: Juniper/contrail-vnc
    check:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-ansible-deployer
    check:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-deployers-containers
    check:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-container-builder
    check:
      templates:
        - k8s-manifests
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-centos
        - cleanup
    experimental:
      templates:
        - ansible-os
        - cleanup
      jobs:
        build-centos:
          job-name: build
          depends-on:
            - fetch-sources-centos
          vars:
            CONTRAIL_BUILD_FROM_SOURCE: true

- project:
    name: Juniper/contrail-controller
    check:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-api-client
    check:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-common
    check:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-vrouter
    check:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-analytics
    check:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-test
    check:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-neutron-plugin
    check:
      templates:
        - test-unit
        - ansible-os
        - juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-os
        - juju-os
        - cleanup

- project:
    name: tungstenfabric/tf-helm-deployer
    check:
      templates:
        - helm-k8s
        - helm-os
        - cleanup
    gate:
      templates:
        - helm-k8s
        - helm-os
        - cleanup

- project:
    name: Juniper/contrail-third-party-packages
    check:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-charms
    check:
      streams:
        juju-os:
          voting: false
        juju-k8s:
          voting: false
      templates:
        - juju-k8s
        - juju-os
        - cleanup

- project:
    name: tungstenfabric/tf-tripleo-puppet
    check:
      templates:
        - build-rhel
        #- rhosp
        - cleanup
    gate:
      templates:
        - build-rhel
        #- rhosp
        - cleanup

- project:
    name: Juniper/contrail-tripleo-heat-templates
    check:
      templates:
        - rhosp
        - cleanup
    gate:
      templates:
        - rhosp
        - cleanup

- project:
    name: tungstenfabric/tf-vcenter-fabric-manager
    check:
      templates:
        - test-unit
        - build-centos
        - cleanup
    gate:
      templates:
        - test-unit
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-vcenter-manager
    check:
      templates:
        - test-unit
        - build-centos
        - cleanup
    gate:
      templates:
        - test-unit
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-vcenter-plugin
    check:
      templates:
        - build-centos
        - cleanup
    gate:
      templates:
        - build-centos
        - cleanup
