---

- template:
    name: cleanup
    post-jobs:
      cleanup-pipeline-workers:

- template:
    name: fetch-sources-centos
    jobs:
      fetch-sources-centos:
        job-name: fetch-sources

- template:
    name: build-centos
    parents:
      - fetch-sources-centos
    jobs:
      build-centos:
        job-name: build
        depends-on:
          - fetch-sources-centos

- template:
    name: build-from-src-centos
    parents:
      - fetch-sources-centos
    jobs:
      build-from-src-centos:
        job-name: build
        depends-on:
          - fetch-sources-centos
        vars:
          CONTRAIL_BUILD_FROM_SOURCE: true
          TAG_SUFFIX: -src

- template:
    name: fetch-sources-rhel
    jobs:
      fetch-sources-rhel:
        job-name: fetch-sources
        vars:
          ENVIRONMENT_OS: rhel7
          TAG_SUFFIX: -rhel7

- template:
    name: build-rhel
    parents:
      - fetch-sources-rhel
    jobs:
      build-rhel:
        job-name: build
        depends-on:
          - fetch-sources-rhel
        vars:
          ENVIRONMENT_OS: rhel7
          TAG_SUFFIX: -rhel7

- template:
    name: test-unit
    parents:
      - fetch-sources-centos
    jobs:
      test-unit:
        depends-on:
          - fetch-sources-centos

- template:
    name: test-unit-ui
    parents:
      - fetch-sources-centos
    jobs:
      test-unit-ui:
        job-name: test-unit
        depends-on:
          - fetch-sources-centos
        vars:
          TARGET: ui

- template:
    name: k8s-manifests
    parents:
      - build-centos
    streams:
      k8s-manifests:
        voting: false
    jobs:
      deploy-platform-k8s-manifests:
        stream: k8s-manifests
      deploy-tf-k8s-manifests:
        stream: k8s-manifests
        depends-on:
          - build-centos
          - deploy-platform-k8s-manifests
        vars:
          DEBUG: true
      test-sanity-k8s-manifests:
        job-name: test-sanity
        stream: k8s-manifests
        depends-on:
          - deploy-tf-k8s-manifests
      test-smoke-k8s-manifests:
        job-name: test-smoke
        stream: k8s-manifests
        depends-on:
          - deploy-tf-k8s-manifests
      collect-logs-and-cleanup-k8s-manifests:
        # 1. run after all stream jobs if any of stream jobs was run
        # 2. shouldn't be included into report
        # 3. should not dictate how to wait - wait_for_deps should exit on first fail and do not wait for all
        job-name: collect-logs-and-cleanup
        stream: k8s-manifests
        type: stream-post-hook
        depends-on:
          - deploy-platform-k8s-manifests
          - deploy-tf-k8s-manifests
          - test-sanity-k8s-manifests
          - test-smoke-k8s-manifests

- template:
    name: ansible-k8s
    parents:
      - build-centos
    streams:
      ansible-k8s:
    jobs:
      deploy-platform-ansible-k8s:
        stream: ansible-k8s
        depends-on:
          # temporary solution while we don't have container with ansible-deployer before build
          - build-centos
      deploy-tf-ansible-k8s:
        stream: ansible-k8s
        depends-on:
          - deploy-platform-ansible-k8s
      test-sanity-ansible-k8s:
        job-name: test-sanity
        stream: ansible-k8s
        depends-on:
          - deploy-tf-ansible-k8s
      collect-logs-and-cleanup-ansible-k8s:
        job-name: collect-logs-and-cleanup
        stream: ansible-k8s
        type: stream-post-hook
        depends-on:
          - deploy-platform-ansible-k8s
          - deploy-tf-ansible-k8s
          - test-sanity-ansible-k8s

- template:
    name: ansible-os
    parents:
      - build-centos
    streams:
      ansible-os:
    jobs:
      deploy-platform-ansible-os:
        stream: ansible-os
        depends-on:
          # temporary solution while we don't have container with ansible-deployer before build
          - build-centos
      deploy-tf-ansible-os:
        stream: ansible-os
        depends-on:
          - deploy-platform-ansible-os
      test-sanity-ansible-os:
        job-name: test-sanity
        stream: ansible-os
        depends-on:
          - deploy-tf-ansible-os
      collect-logs-and-cleanup-ansible-os:
        job-name: collect-logs-and-cleanup
        stream: ansible-os
        type: stream-post-hook
        depends-on:
          - deploy-platform-ansible-os
          - deploy-tf-ansible-os
          - test-sanity-ansible-os

- template:
    name: helm-k8s
    parents:
      - build-centos
    streams:
      helm-k8s:
    jobs:
      deploy-platform-helm-k8s:
        stream: helm-k8s
      deploy-tf-helm-k8s:
        stream: helm-k8s
        depends-on:
          - build-centos
          - deploy-platform-helm-k8s
      test-sanity-helm-k8s:
        job-name: test-sanity
        stream: helm-k8s
        depends-on:
          - deploy-tf-helm-k8s
      collect-logs-and-cleanup-helm-k8s:
        job-name: collect-logs-and-cleanup
        stream: helm-k8s
        type: stream-post-hook
        depends-on:
          - deploy-platform-helm-k8s
          - deploy-tf-helm-k8s
          - test-sanity-helm-k8s

- template:
    name: helm-os
    parents:
      - build-centos
    streams:
      helm-os:
    jobs:
      deploy-platform-helm-os:
        stream: helm-os
      deploy-tf-helm-os:
        stream: helm-os
        depends-on:
          - build-centos
          - deploy-platform-helm-os
      test-sanity-helm-os:
        job-name: test-sanity
        stream: helm-os
        depends-on:
          - deploy-tf-helm-os
      collect-logs-and-cleanup-helm-os:
        job-name: collect-logs-and-cleanup
        stream: helm-os
        type: stream-post-hook
        depends-on:
          - deploy-platform-helm-os
          - deploy-tf-helm-os
          - test-sanity-helm-os

- template:
    name: juju-k8s
    parents:
      - build-centos
    streams:
      juju-k8s:
    jobs:
      deploy-platform-juju-k8s:
        stream: juju-k8s
      deploy-tf-juju-k8s:
        stream: juju-k8s
        depends-on:
          - build-centos
          - deploy-platform-juju-k8s
      test-sanity-juju-k8s:
        job-name: test-sanity
        stream: juju-k8s
        depends-on:
          - deploy-tf-juju-k8s
      collect-logs-and-cleanup-juju-k8s:
        job-name: collect-logs-and-cleanup
        stream: juju-k8s
        type: stream-post-hook
        depends-on:
          - deploy-platform-juju-k8s
          - deploy-tf-juju-k8s
          - test-sanity-juju-k8s

- template:
    name: juju-os
    parents:
      - build-centos
    streams:
      juju-os:
    jobs:
      deploy-platform-juju-os:
        stream: juju-os
      deploy-tf-juju-os:
        stream: juju-os
        depends-on:
          - build-centos
          - deploy-platform-juju-os
      test-sanity-juju-os:
        job-name: test-sanity
        stream: juju-os
        depends-on:
          - deploy-tf-juju-os
      collect-logs-and-cleanup-juju-os:
        job-name: collect-logs-and-cleanup
        stream: juju-os
        type: stream-post-hook
        depends-on:
          - deploy-platform-juju-os
          - deploy-tf-juju-os
          - test-sanity-juju-os

- template:
    name: rhosp
    parents:
      - build-rhel
    streams:
      rhosp:
    jobs:
      deploy-platform-rhosp:
        stream: rhosp
      deploy-tf-rhosp:
        stream: rhosp
        depends-on:
          - build-rhel
          - deploy-platform-rhosp
      test-sanity-rhosp:
        job-name: test-sanity
        stream: rhosp
        depends-on:
          - deploy-tf-rhosp
      collect-logs-and-cleanup-rhosp:
        job-name: collect-logs-and-cleanup
        stream: rhosp
        type: stream-post-hook
        depends-on:
          - deploy-platform-rhosp
          - deploy-tf-rhosp
          - test-sanity-rhosp
